/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HooksContextRouteImport } from './routes/hooks/context'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as HooksStateUseStateRouteImport } from './routes/hooks/state/useState'
import { Route as HooksStateUseReducerRouteImport } from './routes/hooks/state/useReducer'
import { Route as HooksStateUseOptimisticRouteImport } from './routes/hooks/state/useOptimistic'
import { Route as HooksStateUseActionStateRouteImport } from './routes/hooks/state/useActionState'
import { Route as HooksRefUseRefRouteImport } from './routes/hooks/ref/useRef'
import { Route as HooksRefUseImperativeHandleRouteImport } from './routes/hooks/ref/useImperativeHandle'
import { Route as HooksPerformanceUseTransitionRouteImport } from './routes/hooks/performance/useTransition'
import { Route as HooksPerformanceUseMemoRouteImport } from './routes/hooks/performance/useMemo'
import { Route as HooksPerformanceUseDeferredValueRouteImport } from './routes/hooks/performance/useDeferredValue'
import { Route as HooksPerformanceUseCallbackRouteImport } from './routes/hooks/performance/useCallback'
import { Route as HooksOthersUseSyncExternalStoreRouteImport } from './routes/hooks/others/useSyncExternalStore'
import { Route as HooksOthersUseIdRouteImport } from './routes/hooks/others/useId'
import { Route as HooksOthersUseDebugValueRouteImport } from './routes/hooks/others/useDebugValue'
import { Route as HooksEffectUseLayoutEffectRouteImport } from './routes/hooks/effect/useLayoutEffect'
import { Route as HooksEffectUseInsertionEffectRouteImport } from './routes/hooks/effect/useInsertionEffect'
import { Route as HooksEffectUseEffectRouteImport } from './routes/hooks/effect/useEffect'
import { Route as DemoFormSimpleRouteImport } from './routes/demo/form.simple'
import { Route as DemoFormAddressRouteImport } from './routes/demo/form.address'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksContextRoute = HooksContextRouteImport.update({
  id: '/hooks/context',
  path: '/hooks/context',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksStateUseStateRoute = HooksStateUseStateRouteImport.update({
  id: '/hooks/state/useState',
  path: '/hooks/state/useState',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksStateUseReducerRoute = HooksStateUseReducerRouteImport.update({
  id: '/hooks/state/useReducer',
  path: '/hooks/state/useReducer',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksStateUseOptimisticRoute = HooksStateUseOptimisticRouteImport.update({
  id: '/hooks/state/useOptimistic',
  path: '/hooks/state/useOptimistic',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksStateUseActionStateRoute =
  HooksStateUseActionStateRouteImport.update({
    id: '/hooks/state/useActionState',
    path: '/hooks/state/useActionState',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksRefUseRefRoute = HooksRefUseRefRouteImport.update({
  id: '/hooks/ref/useRef',
  path: '/hooks/ref/useRef',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksRefUseImperativeHandleRoute =
  HooksRefUseImperativeHandleRouteImport.update({
    id: '/hooks/ref/useImperativeHandle',
    path: '/hooks/ref/useImperativeHandle',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksPerformanceUseTransitionRoute =
  HooksPerformanceUseTransitionRouteImport.update({
    id: '/hooks/performance/useTransition',
    path: '/hooks/performance/useTransition',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksPerformanceUseMemoRoute = HooksPerformanceUseMemoRouteImport.update({
  id: '/hooks/performance/useMemo',
  path: '/hooks/performance/useMemo',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksPerformanceUseDeferredValueRoute =
  HooksPerformanceUseDeferredValueRouteImport.update({
    id: '/hooks/performance/useDeferredValue',
    path: '/hooks/performance/useDeferredValue',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksPerformanceUseCallbackRoute =
  HooksPerformanceUseCallbackRouteImport.update({
    id: '/hooks/performance/useCallback',
    path: '/hooks/performance/useCallback',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksOthersUseSyncExternalStoreRoute =
  HooksOthersUseSyncExternalStoreRouteImport.update({
    id: '/hooks/others/useSyncExternalStore',
    path: '/hooks/others/useSyncExternalStore',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksOthersUseIdRoute = HooksOthersUseIdRouteImport.update({
  id: '/hooks/others/useId',
  path: '/hooks/others/useId',
  getParentRoute: () => rootRouteImport,
} as any)
const HooksOthersUseDebugValueRoute =
  HooksOthersUseDebugValueRouteImport.update({
    id: '/hooks/others/useDebugValue',
    path: '/hooks/others/useDebugValue',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksEffectUseLayoutEffectRoute =
  HooksEffectUseLayoutEffectRouteImport.update({
    id: '/hooks/effect/useLayoutEffect',
    path: '/hooks/effect/useLayoutEffect',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksEffectUseInsertionEffectRoute =
  HooksEffectUseInsertionEffectRouteImport.update({
    id: '/hooks/effect/useInsertionEffect',
    path: '/hooks/effect/useInsertionEffect',
    getParentRoute: () => rootRouteImport,
  } as any)
const HooksEffectUseEffectRoute = HooksEffectUseEffectRouteImport.update({
  id: '/hooks/effect/useEffect',
  path: '/hooks/effect/useEffect',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormSimpleRoute = DemoFormSimpleRouteImport.update({
  id: '/demo/form/simple',
  path: '/demo/form/simple',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoFormAddressRoute = DemoFormAddressRouteImport.update({
  id: '/demo/form/address',
  path: '/demo/form/address',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/hooks/context': typeof HooksContextRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/hooks/effect/useEffect': typeof HooksEffectUseEffectRoute
  '/hooks/effect/useInsertionEffect': typeof HooksEffectUseInsertionEffectRoute
  '/hooks/effect/useLayoutEffect': typeof HooksEffectUseLayoutEffectRoute
  '/hooks/others/useDebugValue': typeof HooksOthersUseDebugValueRoute
  '/hooks/others/useId': typeof HooksOthersUseIdRoute
  '/hooks/others/useSyncExternalStore': typeof HooksOthersUseSyncExternalStoreRoute
  '/hooks/performance/useCallback': typeof HooksPerformanceUseCallbackRoute
  '/hooks/performance/useDeferredValue': typeof HooksPerformanceUseDeferredValueRoute
  '/hooks/performance/useMemo': typeof HooksPerformanceUseMemoRoute
  '/hooks/performance/useTransition': typeof HooksPerformanceUseTransitionRoute
  '/hooks/ref/useImperativeHandle': typeof HooksRefUseImperativeHandleRoute
  '/hooks/ref/useRef': typeof HooksRefUseRefRoute
  '/hooks/state/useActionState': typeof HooksStateUseActionStateRoute
  '/hooks/state/useOptimistic': typeof HooksStateUseOptimisticRoute
  '/hooks/state/useReducer': typeof HooksStateUseReducerRoute
  '/hooks/state/useState': typeof HooksStateUseStateRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/hooks/context': typeof HooksContextRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/hooks/effect/useEffect': typeof HooksEffectUseEffectRoute
  '/hooks/effect/useInsertionEffect': typeof HooksEffectUseInsertionEffectRoute
  '/hooks/effect/useLayoutEffect': typeof HooksEffectUseLayoutEffectRoute
  '/hooks/others/useDebugValue': typeof HooksOthersUseDebugValueRoute
  '/hooks/others/useId': typeof HooksOthersUseIdRoute
  '/hooks/others/useSyncExternalStore': typeof HooksOthersUseSyncExternalStoreRoute
  '/hooks/performance/useCallback': typeof HooksPerformanceUseCallbackRoute
  '/hooks/performance/useDeferredValue': typeof HooksPerformanceUseDeferredValueRoute
  '/hooks/performance/useMemo': typeof HooksPerformanceUseMemoRoute
  '/hooks/performance/useTransition': typeof HooksPerformanceUseTransitionRoute
  '/hooks/ref/useImperativeHandle': typeof HooksRefUseImperativeHandleRoute
  '/hooks/ref/useRef': typeof HooksRefUseRefRoute
  '/hooks/state/useActionState': typeof HooksStateUseActionStateRoute
  '/hooks/state/useOptimistic': typeof HooksStateUseOptimisticRoute
  '/hooks/state/useReducer': typeof HooksStateUseReducerRoute
  '/hooks/state/useState': typeof HooksStateUseStateRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/hooks/context': typeof HooksContextRoute
  '/demo/form/address': typeof DemoFormAddressRoute
  '/demo/form/simple': typeof DemoFormSimpleRoute
  '/hooks/effect/useEffect': typeof HooksEffectUseEffectRoute
  '/hooks/effect/useInsertionEffect': typeof HooksEffectUseInsertionEffectRoute
  '/hooks/effect/useLayoutEffect': typeof HooksEffectUseLayoutEffectRoute
  '/hooks/others/useDebugValue': typeof HooksOthersUseDebugValueRoute
  '/hooks/others/useId': typeof HooksOthersUseIdRoute
  '/hooks/others/useSyncExternalStore': typeof HooksOthersUseSyncExternalStoreRoute
  '/hooks/performance/useCallback': typeof HooksPerformanceUseCallbackRoute
  '/hooks/performance/useDeferredValue': typeof HooksPerformanceUseDeferredValueRoute
  '/hooks/performance/useMemo': typeof HooksPerformanceUseMemoRoute
  '/hooks/performance/useTransition': typeof HooksPerformanceUseTransitionRoute
  '/hooks/ref/useImperativeHandle': typeof HooksRefUseImperativeHandleRoute
  '/hooks/ref/useRef': typeof HooksRefUseRefRoute
  '/hooks/state/useActionState': typeof HooksStateUseActionStateRoute
  '/hooks/state/useOptimistic': typeof HooksStateUseOptimisticRoute
  '/hooks/state/useReducer': typeof HooksStateUseReducerRoute
  '/hooks/state/useState': typeof HooksStateUseStateRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/demo/tanstack-query'
    | '/hooks/context'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/hooks/effect/useEffect'
    | '/hooks/effect/useInsertionEffect'
    | '/hooks/effect/useLayoutEffect'
    | '/hooks/others/useDebugValue'
    | '/hooks/others/useId'
    | '/hooks/others/useSyncExternalStore'
    | '/hooks/performance/useCallback'
    | '/hooks/performance/useDeferredValue'
    | '/hooks/performance/useMemo'
    | '/hooks/performance/useTransition'
    | '/hooks/ref/useImperativeHandle'
    | '/hooks/ref/useRef'
    | '/hooks/state/useActionState'
    | '/hooks/state/useOptimistic'
    | '/hooks/state/useReducer'
    | '/hooks/state/useState'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/demo/tanstack-query'
    | '/hooks/context'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/hooks/effect/useEffect'
    | '/hooks/effect/useInsertionEffect'
    | '/hooks/effect/useLayoutEffect'
    | '/hooks/others/useDebugValue'
    | '/hooks/others/useId'
    | '/hooks/others/useSyncExternalStore'
    | '/hooks/performance/useCallback'
    | '/hooks/performance/useDeferredValue'
    | '/hooks/performance/useMemo'
    | '/hooks/performance/useTransition'
    | '/hooks/ref/useImperativeHandle'
    | '/hooks/ref/useRef'
    | '/hooks/state/useActionState'
    | '/hooks/state/useOptimistic'
    | '/hooks/state/useReducer'
    | '/hooks/state/useState'
  id:
    | '__root__'
    | '/'
    | '/demo/tanstack-query'
    | '/hooks/context'
    | '/demo/form/address'
    | '/demo/form/simple'
    | '/hooks/effect/useEffect'
    | '/hooks/effect/useInsertionEffect'
    | '/hooks/effect/useLayoutEffect'
    | '/hooks/others/useDebugValue'
    | '/hooks/others/useId'
    | '/hooks/others/useSyncExternalStore'
    | '/hooks/performance/useCallback'
    | '/hooks/performance/useDeferredValue'
    | '/hooks/performance/useMemo'
    | '/hooks/performance/useTransition'
    | '/hooks/ref/useImperativeHandle'
    | '/hooks/ref/useRef'
    | '/hooks/state/useActionState'
    | '/hooks/state/useOptimistic'
    | '/hooks/state/useReducer'
    | '/hooks/state/useState'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  HooksContextRoute: typeof HooksContextRoute
  DemoFormAddressRoute: typeof DemoFormAddressRoute
  DemoFormSimpleRoute: typeof DemoFormSimpleRoute
  HooksEffectUseEffectRoute: typeof HooksEffectUseEffectRoute
  HooksEffectUseInsertionEffectRoute: typeof HooksEffectUseInsertionEffectRoute
  HooksEffectUseLayoutEffectRoute: typeof HooksEffectUseLayoutEffectRoute
  HooksOthersUseDebugValueRoute: typeof HooksOthersUseDebugValueRoute
  HooksOthersUseIdRoute: typeof HooksOthersUseIdRoute
  HooksOthersUseSyncExternalStoreRoute: typeof HooksOthersUseSyncExternalStoreRoute
  HooksPerformanceUseCallbackRoute: typeof HooksPerformanceUseCallbackRoute
  HooksPerformanceUseDeferredValueRoute: typeof HooksPerformanceUseDeferredValueRoute
  HooksPerformanceUseMemoRoute: typeof HooksPerformanceUseMemoRoute
  HooksPerformanceUseTransitionRoute: typeof HooksPerformanceUseTransitionRoute
  HooksRefUseImperativeHandleRoute: typeof HooksRefUseImperativeHandleRoute
  HooksRefUseRefRoute: typeof HooksRefUseRefRoute
  HooksStateUseActionStateRoute: typeof HooksStateUseActionStateRoute
  HooksStateUseOptimisticRoute: typeof HooksStateUseOptimisticRoute
  HooksStateUseReducerRoute: typeof HooksStateUseReducerRoute
  HooksStateUseStateRoute: typeof HooksStateUseStateRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/context': {
      id: '/hooks/context'
      path: '/hooks/context'
      fullPath: '/hooks/context'
      preLoaderRoute: typeof HooksContextRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/state/useState': {
      id: '/hooks/state/useState'
      path: '/hooks/state/useState'
      fullPath: '/hooks/state/useState'
      preLoaderRoute: typeof HooksStateUseStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/state/useReducer': {
      id: '/hooks/state/useReducer'
      path: '/hooks/state/useReducer'
      fullPath: '/hooks/state/useReducer'
      preLoaderRoute: typeof HooksStateUseReducerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/state/useOptimistic': {
      id: '/hooks/state/useOptimistic'
      path: '/hooks/state/useOptimistic'
      fullPath: '/hooks/state/useOptimistic'
      preLoaderRoute: typeof HooksStateUseOptimisticRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/state/useActionState': {
      id: '/hooks/state/useActionState'
      path: '/hooks/state/useActionState'
      fullPath: '/hooks/state/useActionState'
      preLoaderRoute: typeof HooksStateUseActionStateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/ref/useRef': {
      id: '/hooks/ref/useRef'
      path: '/hooks/ref/useRef'
      fullPath: '/hooks/ref/useRef'
      preLoaderRoute: typeof HooksRefUseRefRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/ref/useImperativeHandle': {
      id: '/hooks/ref/useImperativeHandle'
      path: '/hooks/ref/useImperativeHandle'
      fullPath: '/hooks/ref/useImperativeHandle'
      preLoaderRoute: typeof HooksRefUseImperativeHandleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/performance/useTransition': {
      id: '/hooks/performance/useTransition'
      path: '/hooks/performance/useTransition'
      fullPath: '/hooks/performance/useTransition'
      preLoaderRoute: typeof HooksPerformanceUseTransitionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/performance/useMemo': {
      id: '/hooks/performance/useMemo'
      path: '/hooks/performance/useMemo'
      fullPath: '/hooks/performance/useMemo'
      preLoaderRoute: typeof HooksPerformanceUseMemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/performance/useDeferredValue': {
      id: '/hooks/performance/useDeferredValue'
      path: '/hooks/performance/useDeferredValue'
      fullPath: '/hooks/performance/useDeferredValue'
      preLoaderRoute: typeof HooksPerformanceUseDeferredValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/performance/useCallback': {
      id: '/hooks/performance/useCallback'
      path: '/hooks/performance/useCallback'
      fullPath: '/hooks/performance/useCallback'
      preLoaderRoute: typeof HooksPerformanceUseCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/others/useSyncExternalStore': {
      id: '/hooks/others/useSyncExternalStore'
      path: '/hooks/others/useSyncExternalStore'
      fullPath: '/hooks/others/useSyncExternalStore'
      preLoaderRoute: typeof HooksOthersUseSyncExternalStoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/others/useId': {
      id: '/hooks/others/useId'
      path: '/hooks/others/useId'
      fullPath: '/hooks/others/useId'
      preLoaderRoute: typeof HooksOthersUseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/others/useDebugValue': {
      id: '/hooks/others/useDebugValue'
      path: '/hooks/others/useDebugValue'
      fullPath: '/hooks/others/useDebugValue'
      preLoaderRoute: typeof HooksOthersUseDebugValueRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/effect/useLayoutEffect': {
      id: '/hooks/effect/useLayoutEffect'
      path: '/hooks/effect/useLayoutEffect'
      fullPath: '/hooks/effect/useLayoutEffect'
      preLoaderRoute: typeof HooksEffectUseLayoutEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/effect/useInsertionEffect': {
      id: '/hooks/effect/useInsertionEffect'
      path: '/hooks/effect/useInsertionEffect'
      fullPath: '/hooks/effect/useInsertionEffect'
      preLoaderRoute: typeof HooksEffectUseInsertionEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/hooks/effect/useEffect': {
      id: '/hooks/effect/useEffect'
      path: '/hooks/effect/useEffect'
      fullPath: '/hooks/effect/useEffect'
      preLoaderRoute: typeof HooksEffectUseEffectRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/simple': {
      id: '/demo/form/simple'
      path: '/demo/form/simple'
      fullPath: '/demo/form/simple'
      preLoaderRoute: typeof DemoFormSimpleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/form/address': {
      id: '/demo/form/address'
      path: '/demo/form/address'
      fullPath: '/demo/form/address'
      preLoaderRoute: typeof DemoFormAddressRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  HooksContextRoute: HooksContextRoute,
  DemoFormAddressRoute: DemoFormAddressRoute,
  DemoFormSimpleRoute: DemoFormSimpleRoute,
  HooksEffectUseEffectRoute: HooksEffectUseEffectRoute,
  HooksEffectUseInsertionEffectRoute: HooksEffectUseInsertionEffectRoute,
  HooksEffectUseLayoutEffectRoute: HooksEffectUseLayoutEffectRoute,
  HooksOthersUseDebugValueRoute: HooksOthersUseDebugValueRoute,
  HooksOthersUseIdRoute: HooksOthersUseIdRoute,
  HooksOthersUseSyncExternalStoreRoute: HooksOthersUseSyncExternalStoreRoute,
  HooksPerformanceUseCallbackRoute: HooksPerformanceUseCallbackRoute,
  HooksPerformanceUseDeferredValueRoute: HooksPerformanceUseDeferredValueRoute,
  HooksPerformanceUseMemoRoute: HooksPerformanceUseMemoRoute,
  HooksPerformanceUseTransitionRoute: HooksPerformanceUseTransitionRoute,
  HooksRefUseImperativeHandleRoute: HooksRefUseImperativeHandleRoute,
  HooksRefUseRefRoute: HooksRefUseRefRoute,
  HooksStateUseActionStateRoute: HooksStateUseActionStateRoute,
  HooksStateUseOptimisticRoute: HooksStateUseOptimisticRoute,
  HooksStateUseReducerRoute: HooksStateUseReducerRoute,
  HooksStateUseStateRoute: HooksStateUseStateRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
